from tkinter import *


def signUp():
    master = Tk()
    master.geometry("300x250")
    master.configure(bg="#94BFA7")
    Label(master, text='First Name',bg="#E0B7B7").grid(row=0)
    Label(master, text='Last Name',bg="#E0B7B7").grid(row=1)
    Label(master, text='Age',bg="#E0B7B7").grid(row=2)
    Label(master, text='Gender',bg="#E0B7B7").grid(row=3)
    Label(master, text='College',bg="#E0B7B7").grid(row=4)
    Label(master, text='Major',bg="#E0B7B7").grid(row=5)
    Label(master, text='Degree Level',bg="#E0B7B7").grid(row=6)
    Label(master, text='Current Occupation',bg="#E0B7B7").grid(row=7)
    first_name = StringVar()
    last_name = StringVar()
    age = IntVar()
    gender = StringVar()
    college = StringVar()
    major = StringVar()
    degree = StringVar()
    occupation = StringVar()
    first_name_entry = Entry(master, textvariable=first_name)
    last_name_entry = Entry(master, textvariable=last_name)
    age_entry = Entry(master)
    gender_entry = Entry(master, textvariable=gender)
    college_entry = Entry(master, textvariable=college)
    major_entry = Entry(master, textvariable=major)
    degree_entry = Entry(master, textvariable=degree)
    occupation_entry = Entry(master, textvariable=occupation)
    
    first_name_entry.grid(row=0, column=1)
    last_name_entry.grid(row=1,column=1)
    age_entry.grid(row=2, column=1)
    gender_entry.grid(row=3, column=1)
    college_entry.grid(row=4, column=1)
    major_entry.grid(row=5, column=1)
    degree_entry.grid(row=6, column=1)
    occupation_entry.grid(row=7, column=1)

    def get_names():  # Use nonlocal to update the global variables
        fname = first_name_entry.get()
        lname = last_name_entry.get()
        age = age_entry.get()
        gender = gender_entry.get()
        college = college_entry.get()
        major = major_entry.get()
        degree = degree_entry.get()
        occupation = occupation_entry.get()
        master.destroy()

    submit_button = Button(master, text="Submit", command=get_names,bg="#E0B7B7")
    submit_button.grid(row=8, columnspan=5)

    master.mainloop()
